### ISSUE TITLE
deprecated add row action and Rows triggers failed when try to select `spreadsheet`

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/gspreadsheets#33]
Description: latest version where spreadsheet could be selected `9dd1c9ccff8289173ccc2c918c4a61e6dbc9574e`

AR: `Cannot read property 'info' of undefined` error thrown when user click on spreadsheet dropdown.
logs
```
TypeError: Cannot read property 'info' of undefined
    at Object.getJSON (/home/apprunner/lib/http-utils.js:53:17)
    at refreshToken (/home/apprunner/lib/oauth-utils.js:43:15)
    at refreshAppToken (/home/apprunner/lib/oauth-utils.js:78:5)
    at Object.refreshTokenPromise (/home/apprunner/lib/oauth-utils.js:88:5)
    at ServiceExec.listSpreadsheets (/home/apprunner/lib/common.js:135:14)
    at /home/apprunner/node_modules/elasticio-sailor-nodejs/lib/service.js:265:62
    at new Promise (<anonymous>)
    at executeMethod (/home/apprunner/node_modules/elasticio-sailor-nodejs/lib/service.js:258:20)
    at _fulfilled (/home/apprunner/node_modules/elasticio-sailor-nodejs/node_modules/q/q.js:834:54)
    at /home/apprunner/node_modules/elasticio-sailor-nodejs/node_modules/q/q.js:863:30
```

ER: available to interact spreadsheets are shown in dropdown

**Comment by stas-fomenko** [comment]
https://github.com/elasticio/elasticio/issues/4274
